name: Destroy Snowflake Lakehouse Platform
run-name: >
  Destroy Platform by ${{ github.actor }} on ${{ github.ref_name }}

on:
  workflow_dispatch:

concurrency:
  group: terraform-destroy-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write      # needed for OIDC
  contents: read       # needed for checkout / Terraform

jobs:
  terraform-destroy-platform:
    name: Destroy Platform (AWS + Snowflake)
    uses: subhamay-bhattacharyya-gha/terraform-destroy-wf/.github/workflows/terraform-destroy.yaml@feature/GHA-0032-add-platform-based-multi
    with:
      cloud-provider: platform
      backend-type: remote
      aws-region: ${{ vars.AWS_REGION }}
      snowflake-user: ${{ vars.SNOWFLAKE_USER }}
      snowflake-organization-name: ${{ vars.SNOWFLAKE_ORGANIZATION_NAME }}
      snowflake-account-name: ${{ vars.SNOWFLAKE_ACCOUNT_NAME }}
      snowflake-role: ${{ vars.SNOWFLAKE_ROLE }}
    secrets:
      tfc-token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
      aws-role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
      snowflake-private-key: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
